<a href="https://colab.research.google.com/github/Jirapongs55/CP3-Jirapong-Sirichottanawong/blob/main/Copy_of_Week9_PK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Week9

https://colab.research.google.com/drive/1u9UtBFgnJKxroV3h7XJw7JxbPaGuHGlL?usp=sharing

Reference
- https://pbpython.com/plotly-look.html
- https://www.kaggle.com/crawford/80-cereals >> data set
- http://seaborn.pydata.org/examples/index.html

In [4]:
import pandas as pd
import plotly.express as px
import seaborn as sns

df = pd.read_csv('https://github.com/chris1610/pbpython/blob/master/data/cereal_data.csv?raw=True')
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,cereal
0,100% Bran,Nabisco,Cold,70,4,1,130,10.0,5.0,6,280,25,Top,1.0,0.33,68.40,1
1,100% Natural Bran,Quaker Oats,Cold,120,3,5,15,2.0,8.0,8,135,0,Top,1.0,1.00,33.98,1
2,All-Bran,Kellogs,Cold,70,4,1,260,9.0,7.0,5,320,25,Top,1.0,0.33,59.43,1
3,All-Bran with Extra Fiber,Kellogs,Cold,50,4,0,140,14.0,8.0,0,330,25,Top,1.0,0.50,93.70,1
4,Almond Delight,Ralston Purina,Cold,110,2,2,200,1.0,14.0,8,-1,25,Top,1.0,0.75,34.38,1

In [5]:
df.shape

(77, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64
 10  potass    77 non-null     int64
 11  vitamins  77 non-null     int64
 12  shelf     77 non-null     object
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
 16  cereal    77 non-null     int64
dtypes: float64(5), int64(8), object(4)
memory usage: 10.4+ KB

In [7]:
df['shelf'].unique()

array(['Top', 'Bottom', 'Middle'], dtype=object)

#### Reference: https://plotly.com/python-api-reference/generated/plotly.express.scatter

In [8]:
fig = px.scatter(df,
                x='sugars',
                y='rating',
                #hover_name='name',
                color = 'shelf',
                size = 'cups',
                hover_data=['calories','carbo'],
                hover_name= df['name'].astype(str)+" : "+df['mfr'].astype(str),
                title='Cereal_ratings VS Sugars')
fig.show()

In [9]:
# prompt: Which rows contain -1 values?

rows_with_negative_one = df[df.eq(-1).any(axis=1)]
rows_with_negative_one

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,cereal
4,Almond Delight,Ralston Purina,Cold,110,2,2,200,1.0,14.0,8,-1,25,Top,1.0,0.75,34.38,1
20,Cream of Wheat (Quick),Nabisco,Hot,100,3,0,80,1.0,21.0,0,-1,0,Middle,1.0,1.00,64.53,1
57,Quaker Oatmeal,Quaker Oats,Hot,100,5,2,0,2.7,-1.0,-1,110,0,Bottom,1.0,0.67,50.83,1

#Need to fix Quaker Oatmeal error

In [10]:
#df[df['carbo'] == -1]

In [11]:
fig = px.box(df,
                x='sugars',
                y='rating',
                hover_name='name',
                title='Cereal ratings vs. sugars')
                #points="all") #default is the outlier
fig.show()

In [12]:
fig = px.histogram(df, x='sugars', title='Rating distribution', nbins=5) #,nbins=20,cumulative=True)
fig.show()

In [13]:
fig = px.scatter(df,
                x='sugars',
                y='rating',
                color='mfr',
                size='calories',
                facet_row='shelf',
                facet_col='type',
                hover_name='name',
                category_orders={'shelf': ['Top', 'Middle', 'Bottom']})
fig.show()
print(df.head())

                        name             mfr  type  calories  protein  fat  \
0                  100% Bran         Nabisco  Cold        70        4    1
1          100% Natural Bran     Quaker Oats  Cold       120        3    5
2                   All-Bran         Kellogs  Cold        70        4    1
3  All-Bran with Extra Fiber         Kellogs  Cold        50        4    0
4             Almond Delight  Ralston Purina  Cold       110        2    2

   sodium  fiber  carbo  sugars  potass  vitamins shelf  weight  cups  rating  \
0     130   10.0    5.0       6     280        25   Top     1.0  0.33   68.40
1      15    2.0    8.0       8     135         0   Top     1.0  1.00   33.98
2     260    9.0    7.0       5     320        25   Top     1.0  0.33   59.43
3     140   14.0    8.0       0     330        25   Top     1.0  0.50   93.70
4     200    1.0   14.0       8      -1        25   Top     1.0  0.75   34.38

   cereal
0       1
1       1
2       1
3       1
4       1

In [14]:
fig = px.treemap(df, path=['mfr', 'shelf','calories','name'], values='cereal', title='Cereals by shelf location')   #title is information
fig.show()

In [15]:
fig = px.sunburst(df, path=['mfr','calories','sugars','name'], values='cereal')
fig.show()

HW1.
1. Replace SVC with Logistic Regression
2. R&D Feature selection technique and apply to this HW, e.g., Random forest, RFE (SkLearn), etc.
3. Cross Validation (GridSearchCV) (80%/20%)
4. Goal is to improve the accuracy.

In [16]:
!pip install duckdb

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)

In [26]:
import duckdb
import IPython
from IPython.display import display

In [27]:
df = pd.read_csv("/content/cars.csv",sep = ";")

In [30]:
df = df.loc[1:]

In [32]:
df.shape

(406, 9)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 1 to 406
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           406 non-null    object
 1   MPG           406 non-null    object
 2   Cylinders     406 non-null    object
 3   Displacement  406 non-null    object
 4   Horsepower    406 non-null    object
 5   Weight        406 non-null    object
 6   Acceleration  406 non-null    object
 7   Model         406 non-null    object
 8   Origin        406 non-null    object
dtypes: object(9)
memory usage: 28.7+ KB

In [36]:
df.describe(include="all")

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
count,406,406,406,406,406,406,406,406,406
unique,308,130,5,83,94,356,97,13,3
top,Toyota Corolla,13.0,4,97.00,150.0,2130.,14.5,73,US
freq,9,20,207,22,22,4,23,40,254

In [52]:
results = duckdb.sql("select * from df").df()
df.loc[:, "MPG":"Model"] = df.loc[:, "MPG":"Model"].apply(pd.to_numeric, errors="coerce")
display(results)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US
1,Buick Skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US
2,Plymouth Satellite,18.0,8,318.0,150.0,3436.0,11.0,70,US
3,AMC Rebel SST,16.0,8,304.0,150.0,3433.0,12.0,70,US
4,Ford Torino,17.0,8,302.0,140.0,3449.0,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4,140.0,86.0,2790.0,15.6,82,US
402,Volkswagen Pickup,44.0,4,97.0,52.0,2130.0,24.6,82,Europe
403,Dodge Rampage,32.0,4,135.0,84.0,2295.0,11.6,82,US
404,Ford Ranger,28.0,4,120.0,79.0,2625.0,18.6,82,US
405,Chevy S-10,31.0,4,119.0,82.0,2720.0,19.4,82,US

In [56]:
results2 = duckdb.sql("select Origin, avg(MPG) from df group by Origin order by avg(MPG) desc")
display(results2)

┌─────────┬────────────────────┐
│ Origin  │      avg(MPG)      │
│ varchar │       double       │
├─────────┼────────────────────┤
│ Japan   │ 30.450632911392397 │
│ Europe  │ 26.745205479452057 │
│ US      │ 19.688188976377948 │
└─────────┴────────────────────┘

In [57]:
results3 = duckdb.sql("select Cylinders, avg(Displacement) from df group by Cylinders order by avg(Displacement) desc")
display(results3)

┌───────────┬────────────────────┐
│ Cylinders │ avg(Displacement)  │
│   int64   │       double       │
├───────────┼────────────────────┤
│         8 │  345.2037037037037 │
│         6 │ 218.14285714285714 │
│         5 │              145.0 │
│         4 │ 109.90096618357488 │
│         3 │               72.5 │
└───────────┴────────────────────┘

In [55]:
display(df.loc[:, "Model"].unique())

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], dtype=object)

In [78]:
results4 = duckdb.sql("select Origin, Model, avg(Weight), avg(Cylinders) from df group by Origin, Model order by avg(Weight) asc")
display(type(results4))
display(results4)

duckdb.duckdb.DuckDBPyRelation

┌─────────┬───────┬────────────────────┬───────────────────┐
│ Origin  │ Model │    avg(Weight)     │  avg(Cylinders)   │
│ varchar │ int32 │       double       │      double       │
├─────────┼───────┼────────────────────┼───────────────────┤
│ Japan   │    71 │             1936.0 │               4.0 │
│ Japan   │    79 │             1997.5 │               4.0 │
│ Europe  │    71 │             2014.8 │               4.0 │
│ Japan   │    74 │             2053.0 │               4.0 │
│ Europe  │    82 │             2055.0 │               4.0 │
│ Japan   │    82 │  2132.777777777778 │               4.0 │
│ Europe  │    77 │            2138.75 │               4.0 │
│ Europe  │    74 │ 2139.3333333333335 │               4.0 │
│ Japan   │    76 │             2217.5 │               4.5 │
│ Japan   │    78 │            2221.25 │               4.0 │
│ ·       │     · │               ·    │                ·  │
│ ·       │     · │               ·    │                ·  │
│ ·       │     · │               ·    │                ·  │
│ US      │    78 │ 3141.1363636363635 │               6.0 │
│ US      │    79 │  3210.217391304348 │ 6.260869565217392 │
│ US      │    71 │             3401.6 │               6.2 │
│ US      │    76 │  3405.409090909091 │ 6.363636363636363 │
│ US      │    77 │             3422.0 │ 6.222222222222222 │
│ US      │    74 │ 3503.3333333333335 │ 6.266666666666667 │
│ US      │    75 │             3533.2 │               6.4 │
│ US      │    72 │ 3682.6666666666665 │ 6.888888888888889 │
│ US      │    70 │ 3752.1481481481483 │ 7.703703703703703 │
│ US      │    73 │  3821.448275862069 │ 7.241379310344827 │
├─────────┴───────┴────────────────────┴───────────────────┤
│ 39 rows (20 shown)                             4 columns │
└──────────────────────────────────────────────────────────┘

In [83]:
# Graph by Plotly
df4 = results4.fetchdf()
fig = px.scatter(df4,
                 x = df4.iloc[:, 1], y=df4.iloc[:,2],
                 color="Origin", size="avg(Cylinders)",
                 text="Origin", symbol = "Origin")
fig.update_layout(
    xaxis_title="Model_year",
    yaxis_title="Weight",
    title="Car weight vs. model year by origin",
)
fig.show()

In [87]:
df_chipotle = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")

In [108]:
display(df_chipotle)
display(df_chipotle.info())
df_chipotle["item_price"] = df_chipotle["item_price"].str.replace("$", "")
df_chipotle["item_price"] = df_chipotle["item_price"].apply(pd.to_numeric)
display(df_chipotle.info())

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

None

KeyError: 'item_name'

In [117]:
display(df.loc[df["item_name"]=="Chicken Bowl",:])

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49
...,...,...,...,...,...
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",8.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75

In [103]:
df = df_chipotle

In [124]:
df.shape

(4622, 5)

In [126]:
results1 = duckdb.sql("select item_name, count(order_id), sum(item_price), sum(item_price)/count(order_id) from df group by item_name having count(order_id)>=10  order by sum(item_price)/count(order_id) desc")
display(results1)

┌───────────────────────────────────────┬─────────────────┬────────────────────┬─────────────────────────────────────┐
│               item_name               │ count(order_id) │  sum(item_price)   │ (sum(item_price) / count(order_id)) │
│                varchar                │      int64      │       double       │               double                │
├───────────────────────────────────────┼─────────────────┼────────────────────┼─────────────────────────────────────┤
│ Steak Salad Bowl                      │              29 │ 343.58999999999975 │                   11.84793103448275 │
│ Chicken Salad Bowl                    │             110 │            1228.75 │                  11.170454545454545 │
│ Barbacoa Crispy Tacos                 │              11 │             120.21 │                  10.928181818181818 │
│ Carnitas Bowl                         │              68 │  736.7100000000003 │                  10.833970588235298 │
│ Steak Bowl                            │             211 │ 2260.1900000000005 │                  10.711800947867301 │
│ Barbacoa Salad Bowl                   │              10 │              106.4 │                               10.64 │
│ Steak Burrito                         │             368 │  3851.429999999991 │                  10.465842391304324 │
│ Veggie Bowl                           │              85 │  867.9900000000002 │                  10.211647058823532 │
│ Steak Crispy Tacos                    │              35 │ 357.34000000000003 │                  10.209714285714286 │
│ Barbacoa Bowl                         │              66 │  672.3600000000001 │                   10.18727272727273 │
│       ·                               │               · │          ·         │                           ·         │
│       ·                               │               · │          ·         │                           ·         │
│       ·                               │               · │          ·         │                           ·         │
│ Chips and Roasted Chili Corn Salsa    │              22 │  67.85000000000002 │                  3.0840909090909103 │
│ Chips and Tomatillo Red Chili Salsa   │              48 │ 147.50000000000003 │                  3.0729166666666674 │
│ Chips and Tomatillo-Red Chili Salsa   │              20 │  59.75000000000001 │                  2.9875000000000003 │
│ Chips and Tomatillo-Green Chili Salsa │              31 │              78.87 │                   2.544193548387097 │
│ Chips and Roasted Chili-Corn Salsa    │              18 │              43.02 │                                2.39 │
│ Chips                                 │             211 │  494.3399999999984 │                   2.342843601895727 │
│ Bottled Water                         │             162 │ 302.56000000000006 │                  1.8676543209876546 │
│ Side of Chips                         │             101 │ 185.89999999999984 │                   1.840594059405939 │
│ Canned Soft Drink                     │             301 │             438.75 │                  1.4576411960132891 │
│ Canned Soda                           │             104 │ 137.34000000000026 │                  1.3205769230769255 │
├───────────────────────────────────────┴─────────────────┴────────────────────┴─────────────────────────────────────┤
│ 37 rows (20 shown)                                                                                       4 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘